package xyz.tomd.customerservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * 2024-10-14T09:28:07.164+02:00
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://customerservice.tomd.xyz/", name = "CustomerService")
@XmlSeeAlso({xyz.tomd.customerservice.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerService {

    @WebMethod(action = "http://customerservice.tomd.xyz/getCustomers")
    @WebResult(name = "getCustomersResponseElement", targetNamespace = "http://customerservice.tomd.xyz/types/", partName = "parameters")
    public xyz.tomd.customerservice.types.GetCustomersResponseElement getCustomers(

        @WebParam(partName = "parameters", name = "getCustomersElement", targetNamespace = "http://customerservice.tomd.xyz/types/")
        xyz.tomd.customerservice.types.GetCustomersElement parameters
    );
}
